"""Add location column to trafo and new table group trafo

Revision ID: 07b0df20f162
Revises: edd196c78a47
Create Date: 2025-11-06 14:31:14.594970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b0df20f162'
down_revision: Union[str, Sequence[str], None] = 'edd196c78a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Bagian ini SUDAH BENAR karena ini adalah tabel BARU
    # SQLite tidak masalah dengan create_table
    op.create_table('group_trafo',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('kodegrup', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_trafo_id'), 'group_trafo', ['id'], unique=False)
    op.create_index(op.f('ix_group_trafo_name'), 'group_trafo', ['name'], unique=False)

    # --- BAGIAN YANG DIPERBAIKI (untuk tabel 'trafo' yang sudah ada) ---
    # Kita harus menggunakan batch mode untuk memodifikasi tabel 'trafo'
    with op.batch_alter_table('trafo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grupid', sa.Integer(), nullable=True))
        # Memberi nama FK sangat disarankan untuk 'downgrade'
        batch_op.create_foreign_key(
            'fk_trafo_group_trafo_grupid', 
            'group_trafo', 
            ['grupid'], 
            ['id']
        )
    # --- AKHIR PERBAIKAN ---

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # --- BAGIAN YANG DIPERBAIKI (untuk tabel 'trafo' yang sudah ada) ---
    # Kita juga harus menggunakan batch mode untuk downgrade
    with op.batch_alter_table('trafo', schema=None) as batch_op:
        batch_op.drop_constraint('fk_trafo_group_trafo_grupid', type_='foreignkey')
        batch_op.drop_column('grupid')
    # --- AKHIR PERBAIKAN ---

    # Bagian ini SUDAH BENAR karena ini membatalkan create_table
    op.drop_index(op.f('ix_group_trafo_name'), table_name='group_trafo')
    op.drop_index(op.f('ix_group_trafo_id'), table_name='group_trafo')
    op.drop_table('group_trafo')
    
    # ### end Alembic commands ###