"""add table hasil_ka

Revision ID: 1b72e832a8d9
Revises: 07b0df20f162
Create Date: 2025-11-07 22:53:44.289320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b72e832a8d9'
down_revision: Union[str, Sequence[str], None] = '07b0df20f162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hasil_kalkulasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vr', sa.Float(), nullable=False),
    sa.Column('vs', sa.Float(), nullable=False),
    sa.Column('vt', sa.Float(), nullable=False),
    sa.Column('ir', sa.Float(), nullable=False),
    sa.Column('is_', sa.Float(), nullable=False),
    sa.Column('it', sa.Float(), nullable=False),
    sa.Column('cosphi', sa.Float(), nullable=False),
    sa.Column('kvar', sa.Float(), nullable=False),
    sa.Column('kvas', sa.Float(), nullable=False),
    sa.Column('kvat', sa.Float(), nullable=False),
    sa.Column('kwr', sa.Float(), nullable=False),
    sa.Column('kws', sa.Float(), nullable=False),
    sa.Column('kwt', sa.Float(), nullable=False),
    sa.Column('kvar_r', sa.Float(), nullable=False),
    sa.Column('kvar_s', sa.Float(), nullable=False),
    sa.Column('kvar_t', sa.Float(), nullable=False),
    sa.Column('total_kva', sa.Float(), nullable=False),
    sa.Column('total_kw', sa.Float(), nullable=False),
    sa.Column('total_kvar', sa.Float(), nullable=False),
    sa.Column('sisa_kapasitas', sa.Float(), nullable=False),
    sa.Column('tanggal', sa.String(), nullable=False),
    sa.Column('idtrafo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idtrafo'], ['trafo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hasil_kalkulasi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hasil_kalkulasi_id'), ['id'], unique=False)

    with op.batch_alter_table('trafo', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'group_trafo', ['grupid'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trafo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('hasil_kalkulasi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hasil_kalkulasi_id'))

    op.drop_table('hasil_kalkulasi')
    # ### end Alembic commands ###
