"""Initial migration

Revision ID: edd196c78a47
Revises: 
Create Date: 2025-11-05 14:58:47.995306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd196c78a47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trafo', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'trafo', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trafo', type_='foreignkey')
    op.drop_column('trafo', 'owner_id')
    # ### end Alembic commands ###
