"""Initial migration

Revision ID: edd196c78a47
Revises: 
Create Date: 2025-11-05 14:58:47.995306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd196c78a47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Gunakan batch_alter_table untuk SQLite
    with op.batch_alter_table('trafo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_trafo_users_owner_id', 'users', ['owner_id'], ['id'])
        # Catatan: Saya memberi nama 'fk_trafo_users_owner_id' pada foreign key agar 
        # 'downgrade' bisa menemukannya. Menggunakan 'None' bisa bermasalah.

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Gunakan batch_alter_table juga untuk downgrade
    with op.batch_alter_table('trafo', schema=None) as batch_op:
        batch_op.drop_constraint('fk_trafo_users_owner_id', type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###